### PR TITLE
Enhanced wkhtmltopdf to support some options with html content

### PR DESCRIPTION
**Pull request by beroso**
Supported options: header-html, footer-html, cover

### CODE REVIEW

**Comment by klimov-paul** [comment]
Rejected.
These options should be passed as a filenames not the content.

**Comment by beroso** [comment]
I understand your point. The original documentation says that only accepts url or filenames.
But i think this enhancement is convenient for some use cases.
I'm working on a project where all reports have dynamic cover, header and footer. And I compose the pdf like this way:

```
Yii::$app->html2pdf->convert($html, [
    'title' => $title,
    'cover' => $view->render('@app/modules/pj/views/layouts/pdf-cover', [
        'logo' => $logo,
        'company' => $company,
    ]),
    'header-html' => $view->render('@app/modules/pj/views/layouts/pdf-header', [
        'company' => $company,
        'reportTitle' => $reportTitle,
        'filterParams' => $filterParams,
    ]),
    'footer-html' => $view->render('@app/modules/pj/views/layouts/pdf-footer', [
        'date' => $reportDate,
        'user => $user,
    ]),
])
->saveAs($filePath);
```
I think it is expressive, and the component helps me with the temporary files needed in the generation process.
Would you consider this feature? Anyway, I will understand if not.

**Comment by Bhoft** [comment]
I also like the possibility to render the temporary pages. Otherwise this needs an additional class and call to create those files dynamically. Which of course also works.

I am also interested how do you create the cover?
I am using the windows version `wkhtmltopdf 0.12.4 (with patched qt)` and have problems (get an no headers) when trying to add cover + header/footer or an complete error thrown by the exe when adding footer / header margins. 
Which is of course only an issue of wkhtmltopdf  and not by this class.

**Comment by klimov-paul** [comment]
Resolved by commit 38e6b5a9823d3f8563653464b00e6ee55404f607

**Comment by beroso** [comment]
Awesome! Thank you so much.

**Pull request closed without merging**
